title: 7OOP Repository Laboratory and Projects
description: A GitHub Pages site using the Minimal theme with lavender style

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line if not already present

# Optional – useful defaults
show_downloads: false
markdown: kramdown
